apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::318609820353:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-PMREHJRXS1VS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::318609820353:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-05T14:08:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1969"
  uid: 4d8dc4d6-f4d5-4c18-8e4e-6eae589ceb7e
